base_url = "https://rm-o.netlify.app/"
compile_sass = true
output_dir = "docs"
build_search_index = false

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer =true

