base_url = "https://naughty-snyder-535441.netlify.app/"
compile_sass = true
output_dir = "docs"
build_search_index = true

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer =true

[extra]
