[[headers]]
  for = "*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=1,
    must-revalidate'''

[[headers]]
  for = "*.woff2"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/katex/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/webfontloader@1.6.28/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/fonts.css"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/style.css"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''

[[headers]]
  for = "/scripts/script.js"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public,
    max-age=31536000'''
